### ISSUE TITLE
Add a random percentage of empty responses

### ISSUE THREAD

**Issue by samuelweiler** [jkarlin/topics#36]
> If the user opts out of the Topics API, or is in incognito mode, or the user has cleared all of their history, the list of topics returned will be empty...

Seeing how sites now try to detect incognito mode and/or ad blockers and give users of those modes substandard experience, consider making empty responses more normal by providing them in perhaps .5% - 1% of cases.  That might be high enough to discourage the provision of substandard experiences.

**Comment by jkarlin** [comment]
The expectation is that there will be quite a few instances where empty topics are returned, and that it will be challenging to determine if the user is in incognito mode using this. This is something that we can verify, and if turns out not to be the case then we can reconsider.

**Comment by 2br-2b** [comment]
If the goal is to get this on 100% of browsers in the future, then once Topics would be pushed to all users, it will be possible to look at the browser version and see if the user should have Topics enabled. If the browser is at a new enough version and Topics aren't showing up, then you know that the user is in incognito.

According to the spec:

> - If the user opts out of the Topics API, or is in incognito mode, or the user has cleared all of their history, the list of topics returned will be empty
>   - We considered a random response instead of empty but prefer empty because:
>     - It’s clearer to users to see that after disabling the feature, or entering incognito, that no topic is sent
>     - Returning random values would be a loss to utility, for marginal gain in privacy, since the API will return an empty topic for one of many reasons:
>       - The user is in incognito mode
>       - The caller hasn’t seen the topic
>       - The user's browsing history has been cleared
>       - The API is disabled

Thus, an empty API is enough to show that there's a new user, that the API is disabled, or that they're in incognito. Since most users likely won't disable topics if it's on by default, and most users don't regularly clear their browsing history, it seems that most site admins could guess that if a user doesn't have topics, they're either a new user or they're using incognito.

I agree and think that Topics should return nothing every so often for these reasons.

**Comment by michaelkleber** [comment]
@2br-2b I think your analysis isn't taking into account the ["Not every API caller will receive a topic"](https://github.com/jkarlin/topics#:~:text=not%20every%20api%20caller%20will%20receive%20a%20topic) behavior.  When I visit a particular site, there are only 3 topics T1, T2, T3 from the taxonomy that the API might reveal.  If the party calling the API has not also called the API on a site about any of T1, T2, or T3, then the list of topics returned will be empty again.
